"""YOLOv8 训练执行入口。"""

from __future__ import annotations

from backend.service.application.models.yolov8_core.training.checkpoint import (
    YoloV8DetectionEpochCheckpointUpdate,
    build_yolov8_detection_checkpoint_state,
    build_yolov8_detection_epoch_checkpoint_update,
    decode_yolov8_detection_checkpoint_state,
    encode_yolov8_detection_checkpoint_state,
)
from backend.service.application.models.yolov8_core.training.control import (
    YoloV8DetectionEpochControlDecision,
    resolve_yolov8_detection_epoch_control,
)
from backend.service.application.models.yolov8_core.training.dataloader import (
    YoloV8DetectionTrainingDataloaderPlan,
    plan_yolov8_detection_training_dataloader,
)
from backend.service.application.models.yolov8_core.training.detection import (
    compute_yolov8_detection_training_loss,
    is_yolov8_detection_core_model,
)
from backend.service.application.models.yolov8_core.training.detection_execution import (
    YOLOV8_DETECTION_IMPLEMENTATION_MODE,
    YoloV8DetectionTrainingControlCommand,
    YoloV8DetectionTrainingEpochProgress,
    YoloV8DetectionTrainingExecutionRequest,
    YoloV8DetectionTrainingExecutionResult,
    YoloV8DetectionTrainingPausedError,
    YoloV8DetectionTrainingSavePoint,
    YoloV8DetectionTrainingTerminatedError,
    run_yolov8_detection_training,
)
from backend.service.application.models.yolov8_core.training.classification_execution import (
    YOLOV8_CLASSIFICATION_IMPLEMENTATION_MODE,
    YoloV8ClassificationTrainingControlCommand,
    YoloV8ClassificationTrainingEpochProgress,
    YoloV8ClassificationTrainingExecutionRequest,
    YoloV8ClassificationTrainingExecutionResult,
    YoloV8ClassificationTrainingPausedError,
    YoloV8ClassificationTrainingSavePoint,
    YoloV8ClassificationTrainingTerminatedError,
    run_yolov8_classification_training,
)
from backend.service.application.models.yolov8_core.training.segmentation_execution import (
    YOLOV8_SEGMENTATION_IMPLEMENTATION_MODE,
    YoloV8SegmentationTrainingBatchProgress,
    YoloV8SegmentationTrainingControlCommand,
    YoloV8SegmentationTrainingEpochProgress,
    YoloV8SegmentationTrainingExecutionRequest,
    YoloV8SegmentationTrainingExecutionResult,
    YoloV8SegmentationTrainingPausedError,
    YoloV8SegmentationTrainingSavePoint,
    YoloV8SegmentationTrainingTerminatedError,
    run_yolov8_segmentation_training,
)
from backend.service.application.models.yolov8_core.training.pose_execution import (
    YOLOV8_POSE_DEFAULT_EVALUATION_INTERVAL,
    YOLOV8_POSE_IMPLEMENTATION_MODE,
    YoloV8PoseTrainingBatchProgress,
    YoloV8PoseTrainingControlCommand,
    YoloV8PoseTrainingEpochProgress,
    YoloV8PoseTrainingExecutionRequest,
    YoloV8PoseTrainingExecutionResult,
    YoloV8PoseTrainingPausedError,
    YoloV8PoseTrainingSavePoint,
    YoloV8PoseTrainingTerminatedError,
    run_yolov8_pose_training,
)
from backend.service.application.models.yolov8_core.training.obb_execution import (
    YOLOV8_OBB_DEFAULT_EVALUATION_INTERVAL,
    YOLOV8_OBB_IMPLEMENTATION_MODE,
    YoloV8ObbTrainingBatchProgress,
    YoloV8ObbTrainingControlCommand,
    YoloV8ObbTrainingEpochProgress,
    YoloV8ObbTrainingExecutionRequest,
    YoloV8ObbTrainingExecutionResult,
    YoloV8ObbTrainingPausedError,
    YoloV8ObbTrainingSavePoint,
    YoloV8ObbTrainingTerminatedError,
    run_yolov8_obb_training,
)
from backend.service.application.models.yolov8_core.training.epoch import (
    YoloV8DetectionBestMetricUpdate,
    resolve_yolov8_detection_best_metric_name,
    resolve_yolov8_detection_best_metric_update,
    resolve_yolov8_detection_initial_best_metric_value,
    serialize_yolov8_detection_best_metric_value,
    should_run_yolov8_detection_validation,
)
from backend.service.application.models.yolov8_core.training.execution import (
    YoloV8DetectionTrainingDataContext,
    YoloV8DetectionTrainingExecutionPlan,
    plan_yolov8_detection_training_execution,
    prepare_yolov8_detection_training_data_context,
)
from backend.service.application.models.yolov8_core.training.runtime import (
    YoloV8DetectionTrainingRuntime,
    build_yolov8_autocast_context,
    build_yolov8_detection_training_runtime,
    move_yolov8_optimizer_state_to_device,
)
from backend.service.application.models.yolov8_core.training.runner import (
    YoloV8DetectionTrainingBatchProgress,
    YoloV8DetectionTrainingEpochResult,
    run_yolov8_detection_training_epoch,
)
from backend.service.application.models.yolov8_core.training.samples import (
    YoloV8DetectionTrainingSamplePlan,
    plan_yolov8_detection_training_samples,
)
from backend.service.application.models.yolov8_core.training.savepoint import (
    YoloV8DetectionTrainingSavepointPayload,
    build_yolov8_detection_training_savepoint_payload,
)
from backend.service.application.models.yolov8_core.training.resume import (
    YoloV8DetectionResumeValidationRequest,
    validate_yolov8_detection_resume_checkpoint,
)
from backend.service.application.models.yolov8_core.training.validation import (
    evaluate_yolov8_detection_validation_losses,
)

__all__ = [
    "YoloV8DetectionTrainingRuntime",
    "YOLOV8_CLASSIFICATION_IMPLEMENTATION_MODE",
    "YOLOV8_DETECTION_IMPLEMENTATION_MODE",
    "YOLOV8_OBB_DEFAULT_EVALUATION_INTERVAL",
    "YOLOV8_OBB_IMPLEMENTATION_MODE",
    "YOLOV8_POSE_DEFAULT_EVALUATION_INTERVAL",
    "YOLOV8_POSE_IMPLEMENTATION_MODE",
    "YOLOV8_SEGMENTATION_IMPLEMENTATION_MODE",
    "YoloV8DetectionResumeValidationRequest",
    "YoloV8DetectionBestMetricUpdate",
    "YoloV8DetectionEpochControlDecision",
    "YoloV8DetectionEpochCheckpointUpdate",
    "YoloV8ClassificationTrainingControlCommand",
    "YoloV8ClassificationTrainingEpochProgress",
    "YoloV8ClassificationTrainingExecutionRequest",
    "YoloV8ClassificationTrainingExecutionResult",
    "YoloV8ClassificationTrainingPausedError",
    "YoloV8ClassificationTrainingSavePoint",
    "YoloV8ClassificationTrainingTerminatedError",
    "YoloV8DetectionTrainingBatchProgress",
    "YoloV8ObbTrainingBatchProgress",
    "YoloV8ObbTrainingControlCommand",
    "YoloV8ObbTrainingEpochProgress",
    "YoloV8ObbTrainingExecutionRequest",
    "YoloV8ObbTrainingExecutionResult",
    "YoloV8ObbTrainingPausedError",
    "YoloV8ObbTrainingSavePoint",
    "YoloV8ObbTrainingTerminatedError",
    "YoloV8SegmentationTrainingBatchProgress",
    "YoloV8PoseTrainingBatchProgress",
    "YoloV8PoseTrainingControlCommand",
    "YoloV8PoseTrainingEpochProgress",
    "YoloV8PoseTrainingExecutionRequest",
    "YoloV8PoseTrainingExecutionResult",
    "YoloV8PoseTrainingPausedError",
    "YoloV8PoseTrainingSavePoint",
    "YoloV8PoseTrainingTerminatedError",
    "YoloV8SegmentationTrainingControlCommand",
    "YoloV8SegmentationTrainingEpochProgress",
    "YoloV8SegmentationTrainingExecutionRequest",
    "YoloV8SegmentationTrainingExecutionResult",
    "YoloV8SegmentationTrainingPausedError",
    "YoloV8SegmentationTrainingSavePoint",
    "YoloV8SegmentationTrainingTerminatedError",
    "YoloV8DetectionTrainingControlCommand",
    "YoloV8DetectionTrainingDataContext",
    "YoloV8DetectionTrainingDataloaderPlan",
    "YoloV8DetectionTrainingEpochProgress",
    "YoloV8DetectionTrainingEpochResult",
    "YoloV8DetectionTrainingExecutionRequest",
    "YoloV8DetectionTrainingExecutionResult",
    "YoloV8DetectionTrainingExecutionPlan",
    "YoloV8DetectionTrainingPausedError",
    "YoloV8DetectionTrainingSamplePlan",
    "YoloV8DetectionTrainingSavePoint",
    "YoloV8DetectionTrainingSavepointPayload",
    "YoloV8DetectionTrainingTerminatedError",
    "build_yolov8_autocast_context",
    "build_yolov8_detection_checkpoint_state",
    "build_yolov8_detection_epoch_checkpoint_update",
    "build_yolov8_detection_training_runtime",
    "build_yolov8_detection_training_savepoint_payload",
    "compute_yolov8_detection_training_loss",
    "decode_yolov8_detection_checkpoint_state",
    "encode_yolov8_detection_checkpoint_state",
    "evaluate_yolov8_detection_validation_losses",
    "is_yolov8_detection_core_model",
    "move_yolov8_optimizer_state_to_device",
    "plan_yolov8_detection_training_dataloader",
    "plan_yolov8_detection_training_execution",
    "plan_yolov8_detection_training_samples",
    "prepare_yolov8_detection_training_data_context",
    "resolve_yolov8_detection_epoch_control",
    "resolve_yolov8_detection_best_metric_name",
    "resolve_yolov8_detection_best_metric_update",
    "resolve_yolov8_detection_initial_best_metric_value",
    "run_yolov8_detection_training_epoch",
    "run_yolov8_detection_training",
    "run_yolov8_classification_training",
    "run_yolov8_obb_training",
    "run_yolov8_pose_training",
    "run_yolov8_segmentation_training",
    "serialize_yolov8_detection_best_metric_value",
    "should_run_yolov8_detection_validation",
    "validate_yolov8_detection_resume_checkpoint",
]
