"""Conversion Task 类型的唯一事实来源。"""

YOLOX_CONVERSION_TASK_KIND = "yolox-conversion"
YOLOV8_CONVERSION_TASK_KIND = "yolov8-conversion"
YOLO11_CONVERSION_TASK_KIND = "yolo11-conversion"
YOLO26_CONVERSION_TASK_KIND = "yolo26-conversion"
YOLO_MODEL_CONVERSION_TASK_KIND = "yolo-model-conversion"
RFDETR_CONVERSION_TASK_KIND = "rfdetr-conversion"

CONVERSION_TASK_KINDS = (
    YOLOX_CONVERSION_TASK_KIND,
    YOLOV8_CONVERSION_TASK_KIND,
    YOLO11_CONVERSION_TASK_KIND,
    YOLO26_CONVERSION_TASK_KIND,
    YOLO_MODEL_CONVERSION_TASK_KIND,
    RFDETR_CONVERSION_TASK_KIND,
)

__all__ = [
    "CONVERSION_TASK_KINDS",
    "RFDETR_CONVERSION_TASK_KIND",
    "YOLO11_CONVERSION_TASK_KIND",
    "YOLO26_CONVERSION_TASK_KIND",
    "YOLOV8_CONVERSION_TASK_KIND",
    "YOLOX_CONVERSION_TASK_KIND",
    "YOLO_MODEL_CONVERSION_TASK_KIND",
]
