"""RF-DETR 模型规格。"""

from __future__ import annotations
from backend.service.domain.models.model_build_formats import ONNX_BUILD_FORMAT, ONNX_OPTIMIZED_BUILD_FORMAT, OPENVINO_IR_BUILD_FORMAT, TENSORRT_ENGINE_BUILD_FORMAT

RFDETR_MODEL_SCALES = ("nano", "small", "medium", "large")
RFDETR_SUPPORTED_TASKS = ("detection",)
RFDETR_SUPPORTED_BUILD_FORMATS = (ONNX_BUILD_FORMAT, ONNX_OPTIMIZED_BUILD_FORMAT, OPENVINO_IR_BUILD_FORMAT, TENSORRT_ENGINE_BUILD_FORMAT)
RFDETR_DEFAULT_DATASET_FORMAT = "coco-detection-v1"
RFDETR_DEFAULT_INPUT_SIZE = {s: v for s, v in zip(RFDETR_MODEL_SCALES, (384, 512, 576, 704))}
