"""由 workflow_trigger_mailbox.v1.json 自动生成；禁止手工修改。"""

from __future__ import annotations

import struct

CONTRACT_ID = 'amvision.workflow-trigger-mailbox.v1'
SCHEMA_SHA256 = '2b13e8e1f996c8eb38fd01fd23e0349feb3a618ea9e08fe0355d18528f77fdd7'
BYTE_ORDER = "little"
ALIGNMENT_BYTES = 8
MAGIC = bytes.fromhex('414d565754473100')
VERSION = 1
CHECKSUM_ALGORITHM_CRC32_IEEE = 1
RELATIVE_MMAP_PATH = 'workflow-trigger/workflow-trigger-main.mmap'
OWNER_LOCK_SUFFIX = '.owner.lock'
DESCRIPTOR_GUARD_SUFFIX = '.descriptor-{index}.guard'

DESCRIPTOR_COUNT = 128
INLINE_REQUEST_CAPACITY_BYTES = 524288
INLINE_RESPONSE_CAPACITY_BYTES = 524288
OVERFLOW_PAGE_COUNT = 256
OVERFLOW_PAGE_CAPACITY_BYTES = 524288
MAX_OVERFLOW_PAGES_PER_RESPONSE = 64
MAX_REQUEST_BYTES = 524288
MAX_RESPONSE_BYTES = 33554432

FILE_HEADER_STRUCT = struct.Struct('<8sIIIIIIIIIIIIIIQQ48s')
FILE_HEADER_SIZE = 128
FILE_HEADER_MAGIC_OFFSET = 0
FILE_HEADER_VERSION_OFFSET = 8
FILE_HEADER_HEADER_SIZE_OFFSET = 12
FILE_HEADER_DESCRIPTOR_COUNT_OFFSET = 16
FILE_HEADER_DESCRIPTOR_HEADER_SIZE_OFFSET = 20
FILE_HEADER_INLINE_REQUEST_CAPACITY_OFFSET = 24
FILE_HEADER_INLINE_RESPONSE_CAPACITY_OFFSET = 28
FILE_HEADER_DESCRIPTOR_STRIDE_OFFSET = 32
FILE_HEADER_OVERFLOW_PAGE_COUNT_OFFSET = 36
FILE_HEADER_PAGE_HEADER_SIZE_OFFSET = 40
FILE_HEADER_PAGE_CAPACITY_OFFSET = 44
FILE_HEADER_PAGE_STRIDE_OFFSET = 48
FILE_HEADER_MAX_PAGES_PER_RESPONSE_OFFSET = 52
FILE_HEADER_CHECKSUM_ALGORITHM_OFFSET = 56
FILE_HEADER_FLAGS_OFFSET = 60
FILE_HEADER_SERVER_EPOCH_OFFSET = 64
FILE_HEADER_CREATED_AT_NS_OFFSET = 72
FILE_HEADER_RESERVED_OFFSET = 80

DESCRIPTOR_HEADER_STRUCT = struct.Struct('<IIQQ16sQQIIQIIIIQQQQQQQIIIiIIIIIIIIIiIIIIQQQQQII56s')
DESCRIPTOR_HEADER_SIZE = 320
DESCRIPTOR_HEADER_STATE_OFFSET = 0
DESCRIPTOR_HEADER_DESCRIPTOR_INDEX_OFFSET = 4
DESCRIPTOR_HEADER_GENERATION_OFFSET = 8
DESCRIPTOR_HEADER_SERVER_EPOCH_OFFSET = 16
DESCRIPTOR_HEADER_REQUEST_ID_OFFSET = 24
DESCRIPTOR_HEADER_OWNER_TOKEN_OFFSET = 40
DESCRIPTOR_HEADER_DEADLINE_NS_OFFSET = 48
DESCRIPTOR_HEADER_ACCEPTED_TIMEOUT_MS_OFFSET = 56
DESCRIPTOR_HEADER_FLAGS_OFFSET = 60
DESCRIPTOR_HEADER_ROUTE_GENERATION_OFFSET = 64
DESCRIPTOR_HEADER_REQUEST_SIZE_OFFSET = 72
DESCRIPTOR_HEADER_REQUEST_CHECKSUM_ALGORITHM_OFFSET = 76
DESCRIPTOR_HEADER_REQUEST_CHECKSUM_OFFSET = 80
DESCRIPTOR_HEADER_REQUEST_RESERVED_OFFSET = 84
DESCRIPTOR_HEADER_INPUT_LEASE_ID_FINGERPRINT_OFFSET = 88
DESCRIPTOR_HEADER_INPUT_BUFFER_ID_FINGERPRINT_OFFSET = 96
DESCRIPTOR_HEADER_BROKER_EPOCH_OFFSET = 104
DESCRIPTOR_HEADER_BUFFER_GENERATION_OFFSET = 112
DESCRIPTOR_HEADER_BUFFER_OFFSET_OFFSET = 120
DESCRIPTOR_HEADER_BUFFER_CONTENT_LENGTH_OFFSET = 128
DESCRIPTOR_HEADER_MEDIA_TYPE_FINGERPRINT_OFFSET = 136
DESCRIPTOR_HEADER_IMAGE_WIDTH_OFFSET = 144
DESCRIPTOR_HEADER_IMAGE_HEIGHT_OFFSET = 148
DESCRIPTOR_HEADER_IMAGE_CHANNELS_OFFSET = 152
DESCRIPTOR_HEADER_IMAGE_ROW_STRIDE_OFFSET = 156
DESCRIPTOR_HEADER_IMAGE_DTYPE_OFFSET = 160
DESCRIPTOR_HEADER_IMAGE_LAYOUT_OFFSET = 164
DESCRIPTOR_HEADER_IMAGE_PIXEL_FORMAT_OFFSET = 168
DESCRIPTOR_HEADER_IMAGE_FLAGS_OFFSET = 172
DESCRIPTOR_HEADER_RESPONSE_SIZE_OFFSET = 176
DESCRIPTOR_HEADER_RESPONSE_RAW_SIZE_OFFSET = 180
DESCRIPTOR_HEADER_RESPONSE_CODEC_OFFSET = 184
DESCRIPTOR_HEADER_RESPONSE_CHECKSUM_ALGORITHM_OFFSET = 188
DESCRIPTOR_HEADER_RESPONSE_CHECKSUM_OFFSET = 192
DESCRIPTOR_HEADER_FIRST_PAGE_INDEX_OFFSET = 196
DESCRIPTOR_HEADER_RESPONSE_PAGE_COUNT_OFFSET = 200
DESCRIPTOR_HEADER_RESPONSE_OUTPUT_LEASE_COUNT_OFFSET = 204
DESCRIPTOR_HEADER_HANDOFF_STATE_OFFSET = 208
DESCRIPTOR_HEADER_ERROR_CODE_OFFSET = 212
DESCRIPTOR_HEADER_WORKER_INSTANCE_FINGERPRINT_OFFSET = 216
DESCRIPTOR_HEADER_RUNTIME_REVISION_FINGERPRINT_OFFSET = 224
DESCRIPTOR_HEADER_RUNTIME_GENERATION_OFFSET = 232
DESCRIPTOR_HEADER_SNAPSHOT_FINGERPRINT_OFFSET = 240
DESCRIPTOR_HEADER_UPDATED_AT_NS_OFFSET = 248
DESCRIPTOR_HEADER_CANCEL_REQUESTED_OFFSET = 256
DESCRIPTOR_HEADER_RESPONSE_FLAGS_OFFSET = 260
DESCRIPTOR_HEADER_RESERVED_OFFSET = 264

PAGE_HEADER_STRUCT = struct.Struct('<IiIIIIQQQII8s')
PAGE_HEADER_SIZE = 64
PAGE_HEADER_STATE_OFFSET = 0
PAGE_HEADER_NEXT_PAGE_INDEX_OFFSET = 4
PAGE_HEADER_USED_SIZE_OFFSET = 8
PAGE_HEADER_CHECKSUM_ALGORITHM_OFFSET = 12
PAGE_HEADER_CHECKSUM_OFFSET = 16
PAGE_HEADER_DESCRIPTOR_INDEX_OFFSET = 20
PAGE_HEADER_DESCRIPTOR_GENERATION_OFFSET = 24
PAGE_HEADER_OWNER_TOKEN_OFFSET = 32
PAGE_HEADER_SERVER_EPOCH_OFFSET = 40
PAGE_HEADER_ORDINAL_OFFSET = 48
PAGE_HEADER_FLAGS_OFFSET = 52
PAGE_HEADER_RESERVED_OFFSET = 56

DESCRIPTOR_STATE_FREE = 0
DESCRIPTOR_STATE_PREPARE = 1
DESCRIPTOR_STATE_WRITING = 2
DESCRIPTOR_STATE_REQUEST = 3
DESCRIPTOR_STATE_PROCESSING = 4
DESCRIPTOR_STATE_RESPONSE = 5
DESCRIPTOR_STATE_ACKED = 6
DESCRIPTOR_STATE_CANCELLED = 7

PAGE_STATE_FREE = 0
PAGE_STATE_RESERVED = 1
PAGE_STATE_READY = 2

RESPONSE_CODEC_NONE = 0
RESPONSE_CODEC_ZLIB = 1

HANDOFF_STATE_NONE = 0
HANDOFF_STATE_PENDING = 1
HANDOFF_STATE_COMPLETE = 2
HANDOFF_STATE_DETACHED = 3

IMAGE_DTYPE_UNSPECIFIED = 0
IMAGE_DTYPE_UINT8 = 1

IMAGE_LAYOUT_UNSPECIFIED = 0
IMAGE_LAYOUT_HW = 1
IMAGE_LAYOUT_HWC = 2

IMAGE_PIXEL_FORMAT_ENCODED = 0
IMAGE_PIXEL_FORMAT_BGR24 = 1
IMAGE_PIXEL_FORMAT_MONO8 = 2

ERROR_CODE_NONE = 0
ERROR_CODE_INVALID_REQUEST = 1
ERROR_CODE_TRIGGER_SOURCE_NOT_FOUND = 2
ERROR_CODE_ROUTE_GENERATION_MISMATCH = 3
ERROR_CODE_TRIGGER_SOURCE_BUSY = 4
ERROR_CODE_WORKFLOW_RUNTIME_BUSY = 5
ERROR_CODE_WORKFLOW_EXECUTOR_BUSY = 6
ERROR_CODE_LOCAL_BUFFER_CAPACITY_EXHAUSTED = 7
ERROR_CODE_LOCAL_BUFFER_OUTPUT_CAPACITY_EXHAUSTED = 8
ERROR_CODE_TRIGGER_REQUEST_TOO_LARGE = 9
ERROR_CODE_TRIGGER_RESPONSE_TOO_LARGE = 10
ERROR_CODE_TRIGGER_RESPONSE_CAPACITY_EXHAUSTED = 11
ERROR_CODE_CHECKSUM_MISMATCH = 12
ERROR_CODE_IDENTITY_MISMATCH = 13
ERROR_CODE_DEADLINE_EXCEEDED = 14
ERROR_CODE_CANCELLED = 15
ERROR_CODE_WORKFLOW_EXECUTION_FAILED = 16
ERROR_CODE_OUTPUT_HANDOFF_FAILED = 17
ERROR_CODE_PROTOCOL_ERROR = 18
ERROR_CODE_SERVER_UNAVAILABLE = 19
