const zh = {
  resourceType: '资源类型', source: '来源 ID', target: '目标 ID', modelVersion: '模型版本', modelBuild: '模型构建', deployment: '部署实例', size: '大小', origin: '来源', actions: '操作',
  execution: '执行配置', lifecycle: '预热与保活', backendOptions: '后端参数', performanceGoal: '性能目标', keepWarm: '保持设备活跃', keepWarmInterval: '保活间隔（秒）', warmupCount: '预热次数', warmupSize: '预热尺寸', performanceHint: '性能模式', threads: '线程数', streams: '流数', backendKind: '后端类型', executionScope: '执行范围', overflowPolicy: '满载策略', isolationLevel: '隔离级别', coreType: '调度核心类型', hyperThreading: '超线程', cpuPinning: 'CPU 绑核',
  selectFile: '选择部署包', preparing: '正在准备', clear: '清除',
  categories: '类别数', localOrigin: '本地创建', uploadInterrupted: '上传已中止；若记录已受理，可在记录中取消。未提交导入不会创建实例。', import: '导入', export: '导出', importInstance: '导入部署实例', exportInstance: '导出部署实例', records: '部署实例传递记录', transfers: '导入 / 导出', download: '下载', continue: '继续导入', result: '查看结果', cancel: '取消', close: '关闭', done: '完成', check: '检查配置', stopped: '已导入，初始状态为停止', model: '模型', task: '任务', backend: '后端', input: '固定输入', name: '实例名称', device: '设备', count: '实例数', copy: '冲突资源创建副本', configuration: '运行配置', preserve: '保留源实例的运行配置。以下参数仅影响目标实例。', recommended: '使用目标设备的推荐配置', mapping: '资源映射', reuse: '（复用）', sourceDevice: '（源设备）', automatic: '自动选择', invalidCount: '实例数应为 1 到 64 的整数', importedModels: '导入模型', refresh: '刷新', delete: '删除', importOrigin: '部署实例导入', deleteModel: '删除导入模型', deleteModelMessage: '删除模型记录及其文件。仍被使用的模型无法删除。', deleteDetails: '删除实例配置和运行记录。下方列出模型文件的处理范围。', deleteModels: '同时删除导入模型及其文件：', retainModels: '保留模型：',
  uploading: '上传中', pending_export: '等待导出', exporting: '导出中', pending_analysis: '等待分析', analyzing: '分析中', ready: '待导入', needs_attention: '需要处理', pending_import: '等待导入', importing: '导入中', completed: '已完成', failed: '失败', cancelled: '已取消', expired: '已过期',
}
const en: Record<keyof typeof zh, string> = {
  resourceType: 'Resource type', source: 'Source ID', target: 'Target ID', modelVersion: 'Model version', modelBuild: 'Model build', deployment: 'Deployment', size: 'Size', origin: 'Source', actions: 'Actions',
  execution: 'Execution', lifecycle: 'Warmup and keep-alive', backendOptions: 'Backend options', performanceGoal: 'Performance goal', keepWarm: 'Keep device active', keepWarmInterval: 'Keep-alive interval (seconds)', warmupCount: 'Warmup runs', warmupSize: 'Warmup size', performanceHint: 'Performance mode', threads: 'Threads', streams: 'Streams', backendKind: 'Backend type', executionScope: 'Execution scope', overflowPolicy: 'Capacity policy', isolationLevel: 'Isolation level', coreType: 'Scheduling core type', hyperThreading: 'Hyper-threading', cpuPinning: 'CPU pinning',
  selectFile: 'Choose deployment package', preparing: 'Preparing', clear: 'Clear',
  categories: 'Classes', localOrigin: 'Created locally', uploadInterrupted: 'Upload interrupted. Cancel any accepted transfer in the list. No deployment is created until import is confirmed.', import: 'Import', export: 'Export', importInstance: 'Import deployment', exportInstance: 'Export deployment', records: 'Deployment transfers', transfers: 'Imports / exports', download: 'Download', continue: 'Continue import', result: 'View result', cancel: 'Cancel', close: 'Close', done: 'Done', check: 'Check configuration', stopped: 'Imported with both channels initially stopped', model: 'Model', task: 'Task', backend: 'Backend', input: 'Fixed input', name: 'Instance name', device: 'Device', count: 'Instances', copy: 'Create copies for conflicting resources', configuration: 'Runtime configuration', preserve: 'Source configuration is preserved. Changes apply to the target instance.', recommended: 'Use recommended target device configuration', mapping: 'Resource mapping', reuse: ' (reused)', sourceDevice: ' (source device)', automatic: 'Automatic', invalidCount: 'Instances must be an integer from 1 to 64', importedModels: 'Imported models', refresh: 'Refresh', delete: 'Delete', importOrigin: 'Deployment import', deleteModel: 'Delete imported model', deleteModelMessage: 'Delete the model records and files. Models still in use cannot be deleted.', deleteDetails: 'Delete instance configuration and runtime records. Model file handling is listed below.', deleteModels: 'Also delete imported models and files:', retainModels: 'Keep models:',
  uploading: 'Uploading', pending_export: 'Waiting to export', exporting: 'Exporting', pending_analysis: 'Waiting for analysis', analyzing: 'Analyzing', ready: 'Ready to import', needs_attention: 'Needs attention', pending_import: 'Waiting to import', importing: 'Importing', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', expired: 'Expired',
}
export const deploymentTransferMessages = { 'zh-CN': zh, 'en-US': en, 'ja-JP': en, 'ko-KR': en }
