"""YOLO26 classification 训练默认参数。"""

YOLO26_CLASSIFICATION_DEFAULT_INPUT_SIZE = (224, 224)
YOLO26_CLASSIFICATION_DEFAULT_LR = 1e-3
YOLO26_CLASSIFICATION_DEFAULT_WEIGHT_DECAY = 1e-4
YOLO26_CLASSIFICATION_DEFAULT_MIN_LR_RATIO = 0.01


__all__ = [
    "YOLO26_CLASSIFICATION_DEFAULT_INPUT_SIZE",
    "YOLO26_CLASSIFICATION_DEFAULT_LR",
    "YOLO26_CLASSIFICATION_DEFAULT_MIN_LR_RATIO",
    "YOLO26_CLASSIFICATION_DEFAULT_WEIGHT_DECAY",
]

