"""YOLO11 classification 训练默认参数。"""

YOLO11_CLASSIFICATION_DEFAULT_INPUT_SIZE = (224, 224)
YOLO11_CLASSIFICATION_DEFAULT_LR = 1e-2
YOLO11_CLASSIFICATION_DEFAULT_WEIGHT_DECAY = 5e-4
YOLO11_CLASSIFICATION_DEFAULT_MIN_LR_RATIO = 0.01


__all__ = [
    "YOLO11_CLASSIFICATION_DEFAULT_INPUT_SIZE",
    "YOLO11_CLASSIFICATION_DEFAULT_LR",
    "YOLO11_CLASSIFICATION_DEFAULT_MIN_LR_RATIO",
    "YOLO11_CLASSIFICATION_DEFAULT_WEIGHT_DECAY",
]
