"""YOLO26 classification 训练任务服务。"""

from __future__ import annotations

from backend.service.application.models.yolo_primary_classification_training_service import (
    YOLO_PRIMARY_CLASSIFICATION_TRAINING_TASK_KIND,
    YOLO_PRIMARY_CLASSIFICATION_TRAINING_QUEUE_NAME,
    SqlAlchemyYoloPrimaryClassificationTrainingTaskService,
    YoloPrimaryClassificationTrainingTaskRequest,
)

YOLO26_CLASSIFICATION_TRAINING_TASK_KIND = YOLO_PRIMARY_CLASSIFICATION_TRAINING_TASK_KIND
YOLO26_CLASSIFICATION_TRAINING_QUEUE_NAME = YOLO_PRIMARY_CLASSIFICATION_TRAINING_QUEUE_NAME
Yolo26ClassificationTrainingTaskRequest = YoloPrimaryClassificationTrainingTaskRequest
SqlAlchemyYolo26ClassificationTrainingTaskService = SqlAlchemyYoloPrimaryClassificationTrainingTaskService
