<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../launcher/src/Amvar.Launcher.Desktop/Amvar.Launcher.Desktop.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
