"""detection 运行时共享辅助实现。"""

from __future__ import annotations

from backend.service.application.runtime.yolox_detection_runtime import (
    OpenVINOYoloXRuntimeSession as OpenVINODetectionRuntimeSessionBase,
    TensorRTYoloXRuntimeSession as TensorRTDetectionRuntimeSessionBase,
    _DEFAULT_NMS_THRESHOLD as DEFAULT_DETECTION_NMS_THRESHOLD,
    _batched_nms_indices as batched_nms_indices,
    _build_openvino_compile_properties as build_openvino_compile_properties,
    _enable_pytorch_cuda_inference_fast_path as enable_pytorch_cuda_inference_fast_path,
    _ensure_cuda_success as ensure_cuda_success,
    _get_tensorrt_logger as get_tensorrt_logger,
    _import_openvino_module as import_openvino_module,
    _import_tensorrt_module as import_tensorrt_module,
    _import_onnxruntime_module as import_onnxruntime_module,
    _load_prediction_image as load_prediction_image,
    _measure_stage_elapsed_ms as measure_stage_elapsed_ms,
    _measure_cuda_event_elapsed_ms as measure_cuda_event_elapsed_ms,
    _normalize_onnxruntime_outputs as normalize_onnxruntime_outputs,
    _normalize_openvino_outputs as normalize_openvino_outputs,
    _normalize_tensorrt_outputs as normalize_tensorrt_outputs,
    _normalize_tensor_shape as normalize_tensor_shape,
    _prediction_to_numpy_array as prediction_to_numpy_array,
    _preprocess_image as preprocess_image,
    _render_preview_image as render_preview_image,
    _require_cuda_inference_imports as require_cuda_inference_imports,
    _require_inference_imports as require_inference_imports,
    _resolve_cuda_device_index as resolve_cuda_device_index,
    _resolve_cuda_runtime_device_name as resolve_cuda_runtime_device_name,
    _resolve_execution_device_name as resolve_execution_device_name,
    _resolve_numpy_dtype as resolve_numpy_dtype,
    _resolve_onnxruntime_providers as resolve_onnxruntime_providers,
    _resolve_openvino_compiled_runtime_precision as resolve_openvino_compiled_runtime_precision,
    _resolve_openvino_device_name as resolve_openvino_device_name,
    _resolve_openvino_port_dtype as resolve_openvino_port_dtype,
    _resolve_openvino_port_name as resolve_openvino_port_name,
    _resolve_probability as resolve_probability,
    _resolve_tensorrt_dtype_name as resolve_tensorrt_dtype_name,
    _resolve_tensorrt_io_tensor_name as resolve_tensorrt_io_tensor_name,
)


__all__ = [
    "DEFAULT_DETECTION_NMS_THRESHOLD",
    "OpenVINODetectionRuntimeSessionBase",
    "TensorRTDetectionRuntimeSessionBase",
    "batched_nms_indices",
    "build_openvino_compile_properties",
    "enable_pytorch_cuda_inference_fast_path",
    "ensure_cuda_success",
    "get_tensorrt_logger",
    "import_openvino_module",
    "import_onnxruntime_module",
    "import_tensorrt_module",
    "load_prediction_image",
    "measure_cuda_event_elapsed_ms",
    "measure_stage_elapsed_ms",
    "normalize_onnxruntime_outputs",
    "normalize_openvino_outputs",
    "normalize_tensor_shape",
    "normalize_tensorrt_outputs",
    "prediction_to_numpy_array",
    "preprocess_image",
    "render_preview_image",
    "require_cuda_inference_imports",
    "require_inference_imports",
    "resolve_cuda_device_index",
    "resolve_cuda_runtime_device_name",
    "resolve_execution_device_name",
    "resolve_numpy_dtype",
    "resolve_onnxruntime_providers",
    "resolve_openvino_compiled_runtime_precision",
    "resolve_openvino_device_name",
    "resolve_openvino_port_dtype",
    "resolve_openvino_port_name",
    "resolve_probability",
    "resolve_tensorrt_dtype_name",
    "resolve_tensorrt_io_tensor_name",
]
