<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><InternalsVisibleTo Include="Amvar.Launcher.Infrastructure.Tests" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Amvar.Launcher.Core/Amvar.Launcher.Core.csproj" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
