"""REST v1 版本路由定义。"""

from __future__ import annotations

from fastapi import APIRouter

from backend.service.api.rest.v1.routes.classification_conversion_tasks import classification_conversion_tasks_router
from backend.service.api.rest.v1.routes.classification_deployments import classification_deployments_router
from backend.service.api.rest.v1.routes.classification_evaluation_tasks import classification_evaluation_tasks_router
from backend.service.api.rest.v1.routes.classification_inference_tasks import classification_inference_tasks_router
from backend.service.api.rest.v1.routes.classification_training_tasks import classification_training_tasks_router
from backend.service.api.rest.v1.routes.classification_validation_sessions import classification_validation_sessions_router
from backend.service.api.rest.v1.routes.dataset_exports import dataset_exports_router
from backend.service.api.rest.v1.routes.datasets import datasets_router
from backend.service.api.rest.v1.routes.detection_conversion_tasks import detection_conversion_tasks_router
from backend.service.api.rest.v1.routes.detection_deployments import detection_deployments_router
from backend.service.api.rest.v1.routes.detection_evaluation_tasks import detection_evaluation_tasks_router
from backend.service.api.rest.v1.routes.detection_inference_tasks import detection_inference_tasks_router
from backend.service.api.rest.v1.routes.detection_training_tasks import detection_training_tasks_router
from backend.service.api.rest.v1.routes.detection_validation_sessions import (
    detection_validation_sessions_router,
)
from backend.service.api.rest.v1.routes.segmentation_conversion_tasks import segmentation_conversion_tasks_router
from backend.service.api.rest.v1.routes.segmentation_deployments import segmentation_deployments_router
from backend.service.api.rest.v1.routes.segmentation_evaluation_tasks import segmentation_evaluation_tasks_router
from backend.service.api.rest.v1.routes.segmentation_inference_tasks import segmentation_inference_tasks_router
from backend.service.api.rest.v1.routes.segmentation_training_tasks import segmentation_training_tasks_router
from backend.service.api.rest.v1.routes.segmentation_validation_sessions import segmentation_validation_sessions_router
from backend.service.api.rest.v1.routes.pose_conversion_tasks import pose_conversion_tasks_router
from backend.service.api.rest.v1.routes.pose_deployments import pose_deployments_router
from backend.service.api.rest.v1.routes.pose_evaluation_tasks import pose_evaluation_tasks_router
from backend.service.api.rest.v1.routes.pose_inference_tasks import pose_inference_tasks_router
from backend.service.api.rest.v1.routes.pose_training_tasks import pose_training_tasks_router
from backend.service.api.rest.v1.routes.pose_validation_sessions import pose_validation_sessions_router
from backend.service.api.rest.v1.routes.obb_conversion_tasks import obb_conversion_tasks_router
from backend.service.api.rest.v1.routes.obb_deployments import obb_deployments_router
from backend.service.api.rest.v1.routes.obb_evaluation_tasks import obb_evaluation_tasks_router
from backend.service.api.rest.v1.routes.obb_inference_tasks import obb_inference_tasks_router
from backend.service.api.rest.v1.routes.obb_training_tasks import obb_training_tasks_router
from backend.service.api.rest.v1.routes.obb_validation_sessions import obb_validation_sessions_router
from backend.service.api.rest.v1.routes.auth import auth_router
from backend.service.api.rest.v1.routes.models import models_router
from backend.service.api.rest.v1.routes.projects import projects_router
from backend.service.api.rest.v1.routes.system import system_router
from backend.service.api.rest.v1.routes.tasks import tasks_router
from backend.service.api.rest.v1.routes.workflow_runtime import workflow_runtime_router
from backend.service.api.rest.v1.routes.workflow_trigger_sources import workflow_trigger_sources_router
from backend.service.api.rest.v1.routes.workflows import workflows_router


api_v1_router = APIRouter(prefix="/v1")
api_v1_router.include_router(auth_router)
api_v1_router.include_router(system_router)
api_v1_router.include_router(projects_router)
api_v1_router.include_router(workflows_router)
api_v1_router.include_router(workflow_runtime_router)
api_v1_router.include_router(workflow_trigger_sources_router)
api_v1_router.include_router(datasets_router)
api_v1_router.include_router(dataset_exports_router)
api_v1_router.include_router(models_router)
api_v1_router.include_router(detection_training_tasks_router)
api_v1_router.include_router(detection_validation_sessions_router)
api_v1_router.include_router(detection_conversion_tasks_router)
api_v1_router.include_router(detection_deployments_router)
api_v1_router.include_router(detection_inference_tasks_router)
api_v1_router.include_router(detection_evaluation_tasks_router)
api_v1_router.include_router(classification_deployments_router)
api_v1_router.include_router(classification_inference_tasks_router)
api_v1_router.include_router(classification_training_tasks_router)
api_v1_router.include_router(classification_conversion_tasks_router)
api_v1_router.include_router(classification_evaluation_tasks_router)
api_v1_router.include_router(classification_validation_sessions_router)
api_v1_router.include_router(segmentation_deployments_router)
api_v1_router.include_router(segmentation_inference_tasks_router)
api_v1_router.include_router(segmentation_training_tasks_router)
api_v1_router.include_router(segmentation_conversion_tasks_router)
api_v1_router.include_router(segmentation_evaluation_tasks_router)
api_v1_router.include_router(segmentation_validation_sessions_router)
api_v1_router.include_router(pose_deployments_router)
api_v1_router.include_router(pose_inference_tasks_router)
api_v1_router.include_router(pose_training_tasks_router)
api_v1_router.include_router(pose_conversion_tasks_router)
api_v1_router.include_router(pose_validation_sessions_router)
api_v1_router.include_router(pose_evaluation_tasks_router)
api_v1_router.include_router(obb_deployments_router)
api_v1_router.include_router(obb_inference_tasks_router)
api_v1_router.include_router(obb_training_tasks_router)
api_v1_router.include_router(obb_conversion_tasks_router)
api_v1_router.include_router(obb_validation_sessions_router)
api_v1_router.include_router(obb_evaluation_tasks_router)
api_v1_router.include_router(tasks_router)
