<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../launcher/src/Amvar.Launcher.Core/Amvar.Launcher.Core.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />

    <Using Include="Xunit" />
  </ItemGroup>
</Project>
